@BellsLibrary_HostAddress = https://localhost:7022

GET {{BellsLibrary_HostAddress}}/api/book

###


POST {{BellsLibrary_HostAddress}}/api/book
Content-Type: application/json

{
  "id": 0,
  "title": "A autem soluta.",
  "description": "Provident odio harum officia voluptate commodi iusto et hic ut. Qui ullam ut consequuntur. Aliquam dignissimos explicabo assumenda reiciendis corporis. Sed voluptatum ut voluptatem quam quis dolore.",
  "coverImage": "<Binary data>",
  "publicationDate": "2021-11-07 08:20:19.2973571",
  "publisher": "Ebert - Grimes",
  "isbn": "4432650248093",
  "pgCount": 682,
  "category": "Philosophy",
  "author": "Lauriane McClure"
}

###

PUT {{BellsLibrary_HostAddress}}/api/book
Content-Type: application/json

{
  //Book
}

###

GET {{BellsLibrary_HostAddress}}/api/book/23

###

DELETE {{BellsLibrary_HostAddress}}/api/book/23

###
